import puppeteer from 'puppeteer';
import type { YearlyRecap } from './recap.js';

function buildReportHtml(recap: YearlyRecap): string {
  const moveGoal = Math.max(500, Math.round(recap.totalVolume * 0.75));
  const exGoal = Math.max(2000, Math.round(recap.totalMinutes * 0.75));
  const standGoal = Math.max(150, Math.round(recap.activeDays * 0.75));
  const movePct = Math.min(100, (recap.totalVolume / moveGoal) * 100);
  const exPct = Math.min(100, (recap.totalMinutes / exGoal) * 100);
  const standPct = Math.min(100, (recap.activeDays / standGoal) * 100);

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8" />
  <style>
    * { box-sizing: border-box; }
    body { font-family: system-ui, sans-serif; background: linear-gradient(180deg, #0f172a 0%, #020617 100%); color: #e2e8f0; margin: 0; padding: 24px; min-height: 100vh; }
    .card { background: rgba(15,23,42,0.8); border: 1px solid rgba(51,65,85,0.8); border-radius: 24px; padding: 20px; margin-bottom: 16px; }
    h1 { font-size: 24px; margin: 0 0 8px 0; }
    .sub { font-size: 11px; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.2em; }
    .hero { font-size: 36px; font-weight: 600; margin: 8px 0; }
    .grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; }
    .stat { background: rgba(15,23,42,0.6); border-radius: 16px; padding: 12px; }
    .stat-label { font-size: 11px; color: #94a3b8; }
    .stat-value { font-size: 20px; font-weight: 600; margin-top: 4px; }
    .rings { display: flex; justify-content: center; gap: 24px; margin: 16px 0; }
    .ring { text-align: center; }
    .ring svg { width: 80px; height: 80px; }
    .ring-label { font-size: 10px; color: #94a3b8; margin-top: 4px; }
    .ring-value { font-size: 12px; font-weight: 600; }
  </style>
</head>
<body>
  <div class="card">
    <p class="sub">Fitness Year Recap</p>
    <h1>🎉 ${recap.year} 年度总结</h1>
    <p class="hero">${recap.totalWorkouts}</p>
    <p style="font-size:12px;color:#94a3b8">次训练 · ${recap.activeDays} 天活跃 · 最长连续 ${recap.longestStreak} 天</p>
  </div>

  <div class="card">
    <p class="sub">Yearly Rings</p>
    <div class="rings">
      <div class="ring">
        <svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="42" fill="none" stroke="rgba(148,163,184,0.25)" stroke-width="8"/><circle cx="50" cy="50" r="42" fill="none" stroke="#fb7185" stroke-width="8" stroke-dasharray="${264}" stroke-dashoffset="${264 - (264 * movePct) / 100}" stroke-linecap="round" transform="rotate(-90 50 50)"/></svg>
        <div class="ring-label">Move</div>
        <div class="ring-value">${Math.round(recap.totalVolume)}</div>
      </div>
      <div class="ring">
        <svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="42" fill="none" stroke="rgba(148,163,184,0.25)" stroke-width="8"/><circle cx="50" cy="50" r="42" fill="none" stroke="#34d399" stroke-width="8" stroke-dasharray="${264}" stroke-dashoffset="${264 - (264 * exPct) / 100}" stroke-linecap="round" transform="rotate(-90 50 50)"/></svg>
        <div class="ring-label">Exercise (min)</div>
        <div class="ring-value">${recap.totalMinutes}</div>
      </div>
      <div class="ring">
        <svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="42" fill="none" stroke="rgba(148,163,184,0.25)" stroke-width="8"/><circle cx="50" cy="50" r="42" fill="none" stroke="#38bdf8" stroke-width="8" stroke-dasharray="${264}" stroke-dashoffset="${264 - (264 * standPct) / 100}" stroke-linecap="round" transform="rotate(-90 50 50)"/></svg>
        <div class="ring-label">Stand (days)</div>
        <div class="ring-value">${recap.activeDays}</div>
      </div>
    </div>
  </div>

  <div class="card">
    <p class="sub">Key Stats</p>
    <div class="grid">
      <div class="stat"><div class="stat-label">Total Volume</div><div class="stat-value">${Math.round(recap.totalVolume)}</div></div>
      <div class="stat"><div class="stat-label">Total Distance (km)</div><div class="stat-value">${recap.totalDistance.toFixed(1)}</div></div>
      <div class="stat"><div class="stat-label">Best Exercise</div><div class="stat-value">${recap.bestExercise ?? '—'}</div></div>
      <div class="stat"><div class="stat-label">Longest Streak</div><div class="stat-value">${recap.longestStreak} days</div></div>
    </div>
  </div>

  <div class="card">
    <p class="sub">Generated by Fitness Pro</p>
    <p style="font-size:11px;color:#64748b">Grissom Fitness Year Recap · ${new Date().toISOString().slice(0, 10)}</p>
  </div>
</body>
</html>`;
}

export async function generateReportPdf(recap: YearlyRecap): Promise<Buffer> {
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });
  try {
    const page = await browser.newPage();
    await page.setContent(buildReportHtml(recap), { waitUntil: 'networkidle0' });
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '16px', right: '16px', bottom: '16px', left: '16px' },
    });
    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}
